### ISSUE TITLE
Missing flagged icon after refreshing/revisiting a thread

### ISSUE THREAD

**Issue by MdoubleDash** [SOBotics/AdvancedFlagging#44] opened 2020-03-18 16:48 UTC
When I have AdvanceFlagging enabled, the flag icon will be associated with that rather than the native SO "Flag" button. When you flag a post with AdvanceFlagging the red flag icon shows up; however, if you refresh the page or come back to it later, you don't see the red flag anymore and to know whether you acted on the post or not, you have to click on native "Flag" button and see if there's an existing flag from you on this post. 

It would be great to fetch that data and show the red flag icon in case the user has flagged the post earlier.

**Clarification:**

Here's a screenshot of how it looks like when flagging:

![image](https://user-images.githubusercontent.com/18401840/77096131-45575500-69e5-11ea-894c-20f2c793eb7b.png)

If I refresh the same page, the red flag goes away:

![image](https://user-images.githubusercontent.com/18401840/77096257-7768b700-69e5-11ea-89f1-b6e0424f6c06.png)

If I want to know if I have already flagged this or not, I need to open Flag window of SO and it will tell me:

![image](https://user-images.githubusercontent.com/18401840/77096537-d9c1b780-69e5-11ea-8d63-260c562c09ba.png)

However, there's no way to tell if I had acted previously on a post by clicking on AdvanceFlagging.

**Comment by rjrudman** [comment] 2021-01-13 06:43
Sorry for the late response - from memory I believe I completely removed caching that information as it significantly slowed down user's browsers to the point of being usable. For now I'll close this as 'working as intended', but I'd gladly accept any pull request which could cache that information in a performant way (catering to 1000s of entries)

**Comment by rjrudman** [comment] 2021-01-13 06:44
Here's the commit which removed caching: https://github.com/SOBotics/AdvancedFlagging/commit/ae5a8ef7771223a8383ae88768b5112dc0448e35

**Closed by rjrudman** 2021-01-13 06:43 UTC
